### ISSUE TITLE
metadata key naming of `Block` and `Directory`

### ISSUE THREAD

**Issue by nugaon** [fairDataSociety/fairOS-dfs#298]
**Is your feature request related to a problem? Please describe.**
As I noticed FairOS uses snake case for naming keys in JSON objects, but the `Block` interface using different convention:
`Name, Size, CompressedSize, Reference:{ R }`
Additionally, instead of `R`, `swarm` or any other alternative could be used which describes the stored value better.

The directory related metadata has the same problem.

**Describe the solution you'd like**
`name, size, reference:{ swarm }`

Is compression works in FairOS? and if so how?

**Comment by asabya** [comment]
>As I noticed FairOS uses snake case for naming keys in JSON objects, but the Block interface using different convention:
Name, Size, CompressedSize, Reference:{ R }
Additionally, instead of R, swarm or any other alternative could be used which describes the stored value better.

The directory related metadata has the same problem.

As they were only used in fairOS-dfs internally, I was made that way, But now that we have fdp-storage, it makes sense to change it, we are have breaking changes anyway...

Just for reference [BlockInfo](https://github.com/fairDataSociety/fairOS-dfs/blob/ddbfc795e3e2f6fff1a906abf0dc0baf25374a73/pkg/file/inode.go#L25) & [DirMeta](https://github.com/fairDataSociety/fairOS-dfs/blob/ddbfc795e3e2f6fff1a906abf0dc0baf25374a73/pkg/dir/meta.go#L23)

> Is compression works in FairOS? and if so how?

Yes, compression works. we have two types compression available [snappy](https://github.com/golang/snappy) and [gzip](https://github.com/klauspost/pgzip). After we break the data into blocks we compress. Now with the encryption changes in place, we encrypt after compression.

**Comment by nugaon** [comment]
Thanks for your answer.
the most ideal would be to use camelCase tbh since it is the most influential naming JSON keys.
